name: Deploy to GitHub Pages

env:
  NODE_VERSION: 18

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master
  #   paths:
  #     - "website/**"

jobs:
  build:
    name: Build AST Explorer website
    runs-on: ubuntu-latest
    steps:
      - name: Check out to repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
          cache-dependency-path: ./website/yarn.lock

      - name: Install dependencies
        working-directory: ./website
        run: yarn install --frozen-lockfile

      # - name: Run build
      #   working-directory: ./website
      #   run: yarn build

      # Create a dummy build
      - name: Create dummy build
        run: |
          mkdir -p ./out
          echo "Dummy build" > ./out/index.html

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: website
          path: ./out

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out to repository
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: website
          path: ./out

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
