name: Deploy to GitHub Pages

env:
  NODE_VERSION: 18

on:
  push:
    branches:
      - master
    paths:
      - "website/**"
      - ".github/workflows/deploy-to-gh-pages.yml"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build AST Explorer website
    runs-on: ubuntu-latest
    steps:
      - name: Check out to repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
          cache-dependency-path: ./website/yarn.lock

      - name: Install dependencies
        working-directory: ./website
        run: yarn install --frozen-lockfile

      - name: Run build
        working-directory: ./website
        run: yarn build

      - name: Make an artifact named github-pages from build
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
